# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/guillaume/Documents/projets/Str

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/guillaume/Documents/projets/Str

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/guillaume/Documents/projets/Str/CMakeFiles /home/guillaume/Documents/projets/Str/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/guillaume/Documents/projets/Str/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named StrategyGame

# Build rule for target.
StrategyGame: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 StrategyGame
.PHONY : StrategyGame

# fast build rule for target.
StrategyGame/fast:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/build
.PHONY : StrategyGame/fast

src/GUI.o: src/GUI.cpp.o
.PHONY : src/GUI.o

# target to build an object file
src/GUI.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/GUI.cpp.o
.PHONY : src/GUI.cpp.o

src/GUI.i: src/GUI.cpp.i
.PHONY : src/GUI.i

# target to preprocess a source file
src/GUI.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/GUI.cpp.i
.PHONY : src/GUI.cpp.i

src/GUI.s: src/GUI.cpp.s
.PHONY : src/GUI.s

# target to generate assembly for a file
src/GUI.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/GUI.cpp.s
.PHONY : src/GUI.cpp.s

src/action.o: src/action.cpp.o
.PHONY : src/action.o

# target to build an object file
src/action.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/action.cpp.o
.PHONY : src/action.cpp.o

src/action.i: src/action.cpp.i
.PHONY : src/action.i

# target to preprocess a source file
src/action.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/action.cpp.i
.PHONY : src/action.cpp.i

src/action.s: src/action.cpp.s
.PHONY : src/action.s

# target to generate assembly for a file
src/action.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/action.cpp.s
.PHONY : src/action.cpp.s

src/box.o: src/box.cpp.o
.PHONY : src/box.o

# target to build an object file
src/box.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/box.cpp.o
.PHONY : src/box.cpp.o

src/box.i: src/box.cpp.i
.PHONY : src/box.i

# target to preprocess a source file
src/box.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/box.cpp.i
.PHONY : src/box.cpp.i

src/box.s: src/box.cpp.s
.PHONY : src/box.s

# target to generate assembly for a file
src/box.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/box.cpp.s
.PHONY : src/box.cpp.s

src/bucket.o: src/bucket.cpp.o
.PHONY : src/bucket.o

# target to build an object file
src/bucket.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/bucket.cpp.o
.PHONY : src/bucket.cpp.o

src/bucket.i: src/bucket.cpp.i
.PHONY : src/bucket.i

# target to preprocess a source file
src/bucket.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/bucket.cpp.i
.PHONY : src/bucket.cpp.i

src/bucket.s: src/bucket.cpp.s
.PHONY : src/bucket.s

# target to generate assembly for a file
src/bucket.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/bucket.cpp.s
.PHONY : src/bucket.cpp.s

src/buildGround.o: src/buildGround.cpp.o
.PHONY : src/buildGround.o

# target to build an object file
src/buildGround.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/buildGround.cpp.o
.PHONY : src/buildGround.cpp.o

src/buildGround.i: src/buildGround.cpp.i
.PHONY : src/buildGround.i

# target to preprocess a source file
src/buildGround.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/buildGround.cpp.i
.PHONY : src/buildGround.cpp.i

src/buildGround.s: src/buildGround.cpp.s
.PHONY : src/buildGround.s

# target to generate assembly for a file
src/buildGround.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/buildGround.cpp.s
.PHONY : src/buildGround.cpp.s

src/case.o: src/case.cpp.o
.PHONY : src/case.o

# target to build an object file
src/case.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/case.cpp.o
.PHONY : src/case.cpp.o

src/case.i: src/case.cpp.i
.PHONY : src/case.i

# target to preprocess a source file
src/case.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/case.cpp.i
.PHONY : src/case.cpp.i

src/case.s: src/case.cpp.s
.PHONY : src/case.s

# target to generate assembly for a file
src/case.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/case.cpp.s
.PHONY : src/case.cpp.s

src/clickableObject.o: src/clickableObject.cpp.o
.PHONY : src/clickableObject.o

# target to build an object file
src/clickableObject.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/clickableObject.cpp.o
.PHONY : src/clickableObject.cpp.o

src/clickableObject.i: src/clickableObject.cpp.i
.PHONY : src/clickableObject.i

# target to preprocess a source file
src/clickableObject.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/clickableObject.cpp.i
.PHONY : src/clickableObject.cpp.i

src/clickableObject.s: src/clickableObject.cpp.s
.PHONY : src/clickableObject.s

# target to generate assembly for a file
src/clickableObject.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/clickableObject.cpp.s
.PHONY : src/clickableObject.cpp.s

src/engine.o: src/engine.cpp.o
.PHONY : src/engine.o

# target to build an object file
src/engine.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/engine.cpp.o
.PHONY : src/engine.cpp.o

src/engine.i: src/engine.cpp.i
.PHONY : src/engine.i

# target to preprocess a source file
src/engine.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/engine.cpp.i
.PHONY : src/engine.cpp.i

src/engine.s: src/engine.cpp.s
.PHONY : src/engine.s

# target to generate assembly for a file
src/engine.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/engine.cpp.s
.PHONY : src/engine.cpp.s

src/engineConst.o: src/engineConst.cpp.o
.PHONY : src/engineConst.o

# target to build an object file
src/engineConst.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/engineConst.cpp.o
.PHONY : src/engineConst.cpp.o

src/engineConst.i: src/engineConst.cpp.i
.PHONY : src/engineConst.i

# target to preprocess a source file
src/engineConst.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/engineConst.cpp.i
.PHONY : src/engineConst.cpp.i

src/engineConst.s: src/engineConst.cpp.s
.PHONY : src/engineConst.s

# target to generate assembly for a file
src/engineConst.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/engineConst.cpp.s
.PHONY : src/engineConst.cpp.s

src/game.o: src/game.cpp.o
.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i
.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s
.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/ground.o: src/ground.cpp.o
.PHONY : src/ground.o

# target to build an object file
src/ground.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/ground.cpp.o
.PHONY : src/ground.cpp.o

src/ground.i: src/ground.cpp.i
.PHONY : src/ground.i

# target to preprocess a source file
src/ground.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/ground.cpp.i
.PHONY : src/ground.cpp.i

src/ground.s: src/ground.cpp.s
.PHONY : src/ground.s

# target to generate assembly for a file
src/ground.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/ground.cpp.s
.PHONY : src/ground.cpp.s

src/group.o: src/group.cpp.o
.PHONY : src/group.o

# target to build an object file
src/group.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/group.cpp.o
.PHONY : src/group.cpp.o

src/group.i: src/group.cpp.i
.PHONY : src/group.i

# target to preprocess a source file
src/group.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/group.cpp.i
.PHONY : src/group.cpp.i

src/group.s: src/group.cpp.s
.PHONY : src/group.s

# target to generate assembly for a file
src/group.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/group.cpp.s
.PHONY : src/group.cpp.s

src/input.o: src/input.cpp.o
.PHONY : src/input.o

# target to build an object file
src/input.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/input.cpp.o
.PHONY : src/input.cpp.o

src/input.i: src/input.cpp.i
.PHONY : src/input.i

# target to preprocess a source file
src/input.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/input.cpp.i
.PHONY : src/input.cpp.i

src/input.s: src/input.cpp.s
.PHONY : src/input.s

# target to generate assembly for a file
src/input.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/input.cpp.s
.PHONY : src/input.cpp.s

src/interface.o: src/interface.cpp.o
.PHONY : src/interface.o

# target to build an object file
src/interface.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/interface.cpp.o
.PHONY : src/interface.cpp.o

src/interface.i: src/interface.cpp.i
.PHONY : src/interface.i

# target to preprocess a source file
src/interface.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/interface.cpp.i
.PHONY : src/interface.cpp.i

src/interface.s: src/interface.cpp.s
.PHONY : src/interface.s

# target to generate assembly for a file
src/interface.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/interface.cpp.s
.PHONY : src/interface.cpp.s

src/level.o: src/level.cpp.o
.PHONY : src/level.o

# target to build an object file
src/level.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/level.cpp.o
.PHONY : src/level.cpp.o

src/level.i: src/level.cpp.i
.PHONY : src/level.i

# target to preprocess a source file
src/level.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/level.cpp.i
.PHONY : src/level.cpp.i

src/level.s: src/level.cpp.s
.PHONY : src/level.s

# target to generate assembly for a file
src/level.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/level.cpp.s
.PHONY : src/level.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/managerBucket.o: src/managerBucket.cpp.o
.PHONY : src/managerBucket.o

# target to build an object file
src/managerBucket.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/managerBucket.cpp.o
.PHONY : src/managerBucket.cpp.o

src/managerBucket.i: src/managerBucket.cpp.i
.PHONY : src/managerBucket.i

# target to preprocess a source file
src/managerBucket.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/managerBucket.cpp.i
.PHONY : src/managerBucket.cpp.i

src/managerBucket.s: src/managerBucket.cpp.s
.PHONY : src/managerBucket.s

# target to generate assembly for a file
src/managerBucket.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/managerBucket.cpp.s
.PHONY : src/managerBucket.cpp.s

src/map.o: src/map.cpp.o
.PHONY : src/map.o

# target to build an object file
src/map.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/map.cpp.o
.PHONY : src/map.cpp.o

src/map.i: src/map.cpp.i
.PHONY : src/map.i

# target to preprocess a source file
src/map.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/map.cpp.i
.PHONY : src/map.cpp.i

src/map.s: src/map.cpp.s
.PHONY : src/map.s

# target to generate assembly for a file
src/map.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/map.cpp.s
.PHONY : src/map.cpp.s

src/obstacleGround.o: src/obstacleGround.cpp.o
.PHONY : src/obstacleGround.o

# target to build an object file
src/obstacleGround.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/obstacleGround.cpp.o
.PHONY : src/obstacleGround.cpp.o

src/obstacleGround.i: src/obstacleGround.cpp.i
.PHONY : src/obstacleGround.i

# target to preprocess a source file
src/obstacleGround.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/obstacleGround.cpp.i
.PHONY : src/obstacleGround.cpp.i

src/obstacleGround.s: src/obstacleGround.cpp.s
.PHONY : src/obstacleGround.s

# target to generate assembly for a file
src/obstacleGround.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/obstacleGround.cpp.s
.PHONY : src/obstacleGround.cpp.s

src/pathFinder.o: src/pathFinder.cpp.o
.PHONY : src/pathFinder.o

# target to build an object file
src/pathFinder.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/pathFinder.cpp.o
.PHONY : src/pathFinder.cpp.o

src/pathFinder.i: src/pathFinder.cpp.i
.PHONY : src/pathFinder.i

# target to preprocess a source file
src/pathFinder.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/pathFinder.cpp.i
.PHONY : src/pathFinder.cpp.i

src/pathFinder.s: src/pathFinder.cpp.s
.PHONY : src/pathFinder.s

# target to generate assembly for a file
src/pathFinder.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/pathFinder.cpp.s
.PHONY : src/pathFinder.cpp.s

src/player.o: src/player.cpp.o
.PHONY : src/player.o

# target to build an object file
src/player.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/player.cpp.o
.PHONY : src/player.cpp.o

src/player.i: src/player.cpp.i
.PHONY : src/player.i

# target to preprocess a source file
src/player.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/player.cpp.i
.PHONY : src/player.cpp.i

src/player.s: src/player.cpp.s
.PHONY : src/player.s

# target to generate assembly for a file
src/player.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/player.cpp.s
.PHONY : src/player.cpp.s

src/point.o: src/point.cpp.o
.PHONY : src/point.o

# target to build an object file
src/point.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/point.cpp.o
.PHONY : src/point.cpp.o

src/point.i: src/point.cpp.i
.PHONY : src/point.i

# target to preprocess a source file
src/point.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/point.cpp.i
.PHONY : src/point.cpp.i

src/point.s: src/point.cpp.s
.PHONY : src/point.s

# target to generate assembly for a file
src/point.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/point.cpp.s
.PHONY : src/point.cpp.s

src/portrait.o: src/portrait.cpp.o
.PHONY : src/portrait.o

# target to build an object file
src/portrait.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/portrait.cpp.o
.PHONY : src/portrait.cpp.o

src/portrait.i: src/portrait.cpp.i
.PHONY : src/portrait.i

# target to preprocess a source file
src/portrait.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/portrait.cpp.i
.PHONY : src/portrait.cpp.i

src/portrait.s: src/portrait.cpp.s
.PHONY : src/portrait.s

# target to generate assembly for a file
src/portrait.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/portrait.cpp.s
.PHONY : src/portrait.cpp.s

src/rect.o: src/rect.cpp.o
.PHONY : src/rect.o

# target to build an object file
src/rect.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/rect.cpp.o
.PHONY : src/rect.cpp.o

src/rect.i: src/rect.cpp.i
.PHONY : src/rect.i

# target to preprocess a source file
src/rect.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/rect.cpp.i
.PHONY : src/rect.cpp.i

src/rect.s: src/rect.cpp.s
.PHONY : src/rect.s

# target to generate assembly for a file
src/rect.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/rect.cpp.s
.PHONY : src/rect.cpp.s

src/screen.o: src/screen.cpp.o
.PHONY : src/screen.o

# target to build an object file
src/screen.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/screen.cpp.o
.PHONY : src/screen.cpp.o

src/screen.i: src/screen.cpp.i
.PHONY : src/screen.i

# target to preprocess a source file
src/screen.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/screen.cpp.i
.PHONY : src/screen.cpp.i

src/screen.s: src/screen.cpp.s
.PHONY : src/screen.s

# target to generate assembly for a file
src/screen.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/screen.cpp.s
.PHONY : src/screen.cpp.s

src/statusBar.o: src/statusBar.cpp.o
.PHONY : src/statusBar.o

# target to build an object file
src/statusBar.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/statusBar.cpp.o
.PHONY : src/statusBar.cpp.o

src/statusBar.i: src/statusBar.cpp.i
.PHONY : src/statusBar.i

# target to preprocess a source file
src/statusBar.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/statusBar.cpp.i
.PHONY : src/statusBar.cpp.i

src/statusBar.s: src/statusBar.cpp.s
.PHONY : src/statusBar.s

# target to generate assembly for a file
src/statusBar.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/statusBar.cpp.s
.PHONY : src/statusBar.cpp.s

src/uiborder.o: src/uiborder.cpp.o
.PHONY : src/uiborder.o

# target to build an object file
src/uiborder.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/uiborder.cpp.o
.PHONY : src/uiborder.cpp.o

src/uiborder.i: src/uiborder.cpp.i
.PHONY : src/uiborder.i

# target to preprocess a source file
src/uiborder.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/uiborder.cpp.i
.PHONY : src/uiborder.cpp.i

src/uiborder.s: src/uiborder.cpp.s
.PHONY : src/uiborder.s

# target to generate assembly for a file
src/uiborder.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/uiborder.cpp.s
.PHONY : src/uiborder.cpp.s

src/unit.o: src/unit.cpp.o
.PHONY : src/unit.o

# target to build an object file
src/unit.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/unit.cpp.o
.PHONY : src/unit.cpp.o

src/unit.i: src/unit.cpp.i
.PHONY : src/unit.i

# target to preprocess a source file
src/unit.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/unit.cpp.i
.PHONY : src/unit.cpp.i

src/unit.s: src/unit.cpp.s
.PHONY : src/unit.s

# target to generate assembly for a file
src/unit.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/unit.cpp.s
.PHONY : src/unit.cpp.s

src/villager.o: src/villager.cpp.o
.PHONY : src/villager.o

# target to build an object file
src/villager.cpp.o:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/villager.cpp.o
.PHONY : src/villager.cpp.o

src/villager.i: src/villager.cpp.i
.PHONY : src/villager.i

# target to preprocess a source file
src/villager.cpp.i:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/villager.cpp.i
.PHONY : src/villager.cpp.i

src/villager.s: src/villager.cpp.s
.PHONY : src/villager.s

# target to generate assembly for a file
src/villager.cpp.s:
	$(MAKE) -f CMakeFiles/StrategyGame.dir/build.make CMakeFiles/StrategyGame.dir/src/villager.cpp.s
.PHONY : src/villager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... StrategyGame"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/GUI.o"
	@echo "... src/GUI.i"
	@echo "... src/GUI.s"
	@echo "... src/action.o"
	@echo "... src/action.i"
	@echo "... src/action.s"
	@echo "... src/box.o"
	@echo "... src/box.i"
	@echo "... src/box.s"
	@echo "... src/bucket.o"
	@echo "... src/bucket.i"
	@echo "... src/bucket.s"
	@echo "... src/buildGround.o"
	@echo "... src/buildGround.i"
	@echo "... src/buildGround.s"
	@echo "... src/case.o"
	@echo "... src/case.i"
	@echo "... src/case.s"
	@echo "... src/clickableObject.o"
	@echo "... src/clickableObject.i"
	@echo "... src/clickableObject.s"
	@echo "... src/engine.o"
	@echo "... src/engine.i"
	@echo "... src/engine.s"
	@echo "... src/engineConst.o"
	@echo "... src/engineConst.i"
	@echo "... src/engineConst.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/ground.o"
	@echo "... src/ground.i"
	@echo "... src/ground.s"
	@echo "... src/group.o"
	@echo "... src/group.i"
	@echo "... src/group.s"
	@echo "... src/input.o"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/interface.o"
	@echo "... src/interface.i"
	@echo "... src/interface.s"
	@echo "... src/level.o"
	@echo "... src/level.i"
	@echo "... src/level.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/managerBucket.o"
	@echo "... src/managerBucket.i"
	@echo "... src/managerBucket.s"
	@echo "... src/map.o"
	@echo "... src/map.i"
	@echo "... src/map.s"
	@echo "... src/obstacleGround.o"
	@echo "... src/obstacleGround.i"
	@echo "... src/obstacleGround.s"
	@echo "... src/pathFinder.o"
	@echo "... src/pathFinder.i"
	@echo "... src/pathFinder.s"
	@echo "... src/player.o"
	@echo "... src/player.i"
	@echo "... src/player.s"
	@echo "... src/point.o"
	@echo "... src/point.i"
	@echo "... src/point.s"
	@echo "... src/portrait.o"
	@echo "... src/portrait.i"
	@echo "... src/portrait.s"
	@echo "... src/rect.o"
	@echo "... src/rect.i"
	@echo "... src/rect.s"
	@echo "... src/screen.o"
	@echo "... src/screen.i"
	@echo "... src/screen.s"
	@echo "... src/statusBar.o"
	@echo "... src/statusBar.i"
	@echo "... src/statusBar.s"
	@echo "... src/uiborder.o"
	@echo "... src/uiborder.i"
	@echo "... src/uiborder.s"
	@echo "... src/unit.o"
	@echo "... src/unit.i"
	@echo "... src/unit.s"
	@echo "... src/villager.o"
	@echo "... src/villager.i"
	@echo "... src/villager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

